"""Names for latent transition targets declared by SSM specs."""

LATENT_TRANSITION_LOCAL_LINEAR_GAUSSIAN = "local_linear_gaussian"
LATENT_TRANSITION_EULER_MARUYAMA = "euler_maruyama"
LATENT_TRANSITION_KINDS = (
    LATENT_TRANSITION_LOCAL_LINEAR_GAUSSIAN,
    LATENT_TRANSITION_EULER_MARUYAMA,
)
